export const queryKeys = {
  attendance: "attendance",
  auth: "auth",
  dashboard: "dashboard",
  dealer: "dealer",
  dealers: "dealers",
  doctor: "doctor",
  doctors: "doctors",
  employees: "employees",
  mtp: "mtp",
  notifications: "notifications",
  products: "products",
  reports: "reports",
  retailers: "retailers",
  sales: "sales",
  settings: "settings",
  tracking: "tracking",
} as const;